### ISSUE TITLE
Music Refusing to Play

### ISSUE THREAD

**Issue by Flugal** [wyozi/wmc-plus#22]
We use WMCP for event music on our server. 
However, right now, every time I go to play all I get this error:
[HTML] Uncaught TypeError: Property 'warn' of object #<error> is not a function
    at https://www.youtube.com/yts/jsbin/player-en_US-vflp0EuAP/base.js:3977:98
    at new <anonymous> (https://www.youtube.com/yts/jsbin/player-en_US-vflp0EuAP/base.js:3971:132)
    at https://www.youtube.com/yts/jsbin/player-en_US-vflp0EuAP/base.js:6861:321
    at qh.<anonymous> (https://www.youtube.com/yts/jsbin/www-embed-player-vflKsnXPx/www-embed-player.js:423:268)
    at qh.lb (https://www.youtube.com/yts/jsbin/www-embed-player-vflKsnXPx/www-embed-player.js:423:308)
    at uh (https://www.youtube.com/yts/jsbin/www-embed-player-vflKsnXPx/www-embed-player.js:421:143)
    at qh.pa (https://www.youtube.com/yts/jsbin/www-embed-player-vflKsnXPx/www-embed-player.js:414:176)
    at https://www.youtube.com/yts/jsbin/www-embed-player-vflKsnXPx/www-embed-player.js:456:420
[HTML] Uncaught TypeError: Property 'warn' of object #<error> is not a function
    at https://www.youtube.com/yts/jsbin/player-en_US-vflp0EuAP/base.js:3977:98
    at new <anonymous> (https://www.youtube.com/yts/jsbin/player-en_US-vflp0EuAP/base.js:3971:132)
    at https://www.youtube.com/yts/jsbin/player-en_US-vflp0EuAP/base.js:6861:321
    at qh.<anonymous> (https://www.youtube.com/yts/jsbin/www-embed-player-vflKsnXPx/www-embed-player.js:423:268)
    at qh.lb (https://www.youtube.com/yts/jsbin/www-embed-player-vflKsnXPx/www-embed-player.js:423:308)
    at uh (https://www.youtube.com/yts/jsbin/www-embed-player-vflKsnXPx/www-embed-player.js:421:143)
    at qh.pa (https://www.youtube.com/yts/jsbin/www-embed-player-vflKsnXPx/www-embed-player.js:414:176)
    at https://www.youtube.com/yts/jsbin/www-embed-player-vflKsnXPx/www-embed-player.js:456:420

**Comment by wyozi** [comment]
Looks like this may be a quite big problem with how youtube playback is handled. I'll take a closer look later.

**Comment by wyozi** [comment]
Fixed in latest github/workshop version.
